// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login', async function() {
    await driver.get("https://alfred-dev.thrivedx.com/login")
    await driver.manage().window().setRect({ width: 1292, height: 688 })
    await driver.findElement(By.id("login_email")).sendKeys("erezn@hackeruso.com")
    await driver.findElement(By.id("login_password")).sendKeys("S860M5KEUBNQh!f3CgN6")
    await driver.findElement(By.id("login_email")).click()
    await driver.findElement(By.id("login_button")).click()
    await driver.findElement(By.css(".has-submenu:nth-child(4) .ng-star-inserted:nth-child(1) > a")).click()
    {
      const element = await driver.findElement(By.css(".btn-success"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".btn-success")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".pi-times")).click()
    {
      const element = await driver.findElement(By.css(".pro-user-name"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".pro-user-name")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".show > .dropdown-item:nth-child(2) > .btn")).click()
    await driver.findElement(By.id("login_email")).sendKeys("erezn@hackeruso.com")
    await driver.findElement(By.id("login_password")).sendKeys("S860M5KEUBNQh!f3CgN6")
  })
})
